# Generated by Django 5.2.6 on 2025-09-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DishCategory",
            new_name="Category",
        ),
    ]
