# Generated by Django 5.2.6 on 2025-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image_large",
            field=models.ImageField(blank=True, null=True, upload_to="images/avatars/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="image_medium",
            field=models.ImageField(blank=True, null=True, upload_to="images/avatars/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="image_small",
            field=models.ImageField(blank=True, null=True, upload_to="images/avatars/"),
        ),
    ]
